package:
  name: imp
  version: "2.7.0"

source:
  fn: imp-2.7.0.tar.gz
  url: https://integrativemodeling.org/2.7.0/download/imp-2.7.0.tar.gz
  sha256: 877af254567051c78317ea94730dfff742aa56d21aefd71edf14a3f4b153b036
  patches:
    - imp-directories.patch [win]
    - imp-msvc2008-vector-data.patch [win and py27]

build:
  number: 2
  detect_binary_files_with_prefix: True [not win]
  features:
    - vc9 [win and py27]
    - vc14 [win and py36]

requirements:
  build:
    - python
    - swig
    - cgal 4.9.1
    - cmake [not win]
    - cmake-mac [win]
    - boost 1.61.0 [win]
    - boost 1.61.0 [linux]
    - boost 1.61.0 [osx]
    - hdf5 1.8.17
    - fftw 3.3.4
    - libtau
    - gsl 1.8 [win]
    - gsl 1.16 [not win]
    - opencv 2.4.8 [py2k and osx]
    - opencv 2.4.6 [py2k and linux32]
    - opencv 3.1.0 [py2k and linux64]
    - numpy 1.11* [py2k and linux64]
    - opencv-nopython 2.4.9 [py3k or win]

  run:
    - python
    - cgal 4.9.1
    - boost 1.61.0 [win]
    - boost 1.61.0 [linux]
    - boost 1.61.0 [osx]
    - hdf5 1.8.17
    - fftw 3.3.4
    - libtau
    - gsl 1.8 [win]
    - gsl 1.16 [not win]
    - opencv 2.4.8 [py2k and osx]
    - opencv 2.4.6 [py2k and linux32]
    - opencv 3.1.0 [py2k and linux64]
    - numpy 1.11* [py2k and linux64]
    - opencv-nopython 2.4.9 [py3k or win]

test:
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.cnmultifit
    - IMP.em2d
    - IMP.rmf
    - RMF
  # Command line tools
  commands:
    - cnmultifit --help
    - foxs --help

about:
  home: https://integrativemodeling.org
  license: LGPL/GPL
  summary: "The Integrative Modeling Platform"
