package:
  name: glib 
  version: "2.31.2"

source:
  fn: glib-2.31.2.tar.bz2
  url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.31/glib-2.31.2.tar.bz2
  sha256: 964f944f294e4ff15f2a9ba5cc82e746de5f2cbb0e05732d86c8bd3e7c531ca6
  patches: [osx]
    - mac-iconv.patch [osx]

requirements:
  build:
    - zlib
    - gettext
    - libffi [unix]

  run:
    - gettext
    - libffi [unix]

about:
  home: https://developer.gnome.org/glib/stable/
  license: LGPL
  summary: "GNOME core building blocks for C libraries and applications"

