# Tested on Mac OS X 10.9 using clang compiler provided by XCode
package:
    name: opencv-nopython
    version: 2.4.9

source:
    fn: opencv-2.4.9.zip
    url: http://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.9/opencv-2.4.9.zip

build:
    number: 4
    features:
      - vc9 [win and py27]
      - vc14 [win and py35]

requirements:
    build:
        - python [win]
        - cmake [not win]
        - cmake-mac [win]
        - jpeg 9b
        - zlib 1.2.8
        - libpng 1.6.27
        - libtiff 4.0.6
    run:
        - jpeg 9b
        - zlib 1.2.8
        - libpng 1.6.27
        - libtiff 4.0.6

about:
    home: http://opencv.org/
    summary: "opencv package built without Python (for Python 3)"
    license: BSD
