package:
  name: mdt
  version: "5.3"

source:
  fn: mdt-5.3.tar.gz
  url: https://salilab.org/mdt/5.3/mdt-5.3.tar.gz
  sha256: 9ced663387f939cff056daec76760cef6bd99f27c6fb5f04dec96b9e9e1fc1d0
  patches: [unix]
    - mdt-cmake.patch [unix]

build:
  number: 4

requirements:
  build:
    - python
    - numpy
    - modeller 9.18
    - cmake [not osx]
    - cmake-mac [osx]
    - swig
    - glib

  run:
    - python
    - numpy
    - modeller 9.18

about:
  home: https://salilab.org/mdt/
  license: GPL2
  summary: "Generate frequency tables used by Modeller and IMP"
