package:
  name: hdf5-1816 
  version: "1.8.16"

source:
  fn: hdf5-1.8.16.tar.bz2
  url: http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/hdf5-1.8.16.tar.bz2
  sha1: a7b631778cb289edec670f665d2c3265983a0d53
  sha256: 13aaae5ba10b70749ee1718816a4b4bfead897c2fcb72c24176e759aec4598c6

requirements:
  build:
    - zlib

  run:
    - zlib

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD
  summary: "HDF5 pinned at 1.8.16, for use with Modeller"
