package:
  name: hdf5-1817 
  version: "1.8.17"

source:
  fn: hdf5-1.8.17.tar.bz2
  url: http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2
  sha1: 640f1a46cb1b353339695355b4fca42df05be765
  sha256: fc35dd8fd8d398de6b525b27cc111c21fc79795ad6db1b1f12cb15ed1ee8486a

requirements:
  build:
    - zlib

  run:
    - zlib

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD
  summary: "HDF5 pinned at 1.8.17, for use with Modeller"
