package:
  name: libtau
  version: "1.0.1"

source:
  fn: libTAU-1.0.1.zip
  url: http://integrativemodeling.org/libTAU/libTAU-1.0.1.zip
  md5: 060c4a271063dc239d6646d3bbe25b01
  sha256: 8aa352b35370fb6048d9387fcfe01f76d33d65b3f7aaa70e3fb95a7f2b687b12

build:
  number: 0
  features:
    - vc9 [win and py27]
    - vc14 [win and py35]

requirements:
  build:
    - python [win]

about:
  home: https://integrativemodeling.org/libTAU.html
  license: Binary distribution only
  summary: "Support library needed for MultiFit"
