package:
  name: gmp
  version: "5.0.1"

# Use precompiled binaries provided by the CGAL folks (since we're going to
# use them to build CGAL anyway, they should work). The "official" way to get
# them is to run the CGAL installer, but it doesn't seem to be possible to
# run that from a command line - but these are the URLs it hits (may need to
# be changed in the future if the installer goes elsewhere for them).
source:
  fn: gmp-all-CGAL-3.9.zip
  url: https://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/win32/GMP/5.0.1/gmp-all-CGAL-3.9.zip [win32]
  url: https://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/GMP/5.0.1/gmp-all-CGAL-3.9.zip [win64]
  sha256: b01fd082afaddf6eecd8b761634a2014ff6fe231705ec7f802465e7e624c1c10 [win32]
  sha256: 2ecce8ac44eb9d6a562e905e3ee2ee811a94dd8b37a79418b2d6fc3559e61c3d [win64]

build:
  number: 0

about:
  home: http://gmplib.org
  license: LGPLv3
  summary: "The GNU Multiple Precision Arithmetic Library (for Windows)"
